include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_AEE_FEATURE)	+= common/
obj-$(CONFIG_MTK_AEE_FEATURE)	+= aed/
obj-$(CONFIG_MTK_AEE_FEATURE)	+= ipanic/
obj-$(CONFIG_MTK_AEE_FEATURE)   += mrdump/
