/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb  9 22:02:07 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


