# drivers/image/gdma/Makefile

EXTRA_CFLAGS = -DSDEBUG_T

obj-y += gdma_driver.o

gdma_driver-objs := gdma_drv_6589_ctl.o gdma_drv.o

obj-y += gfmt_driver.o

gfmt_driver-objs := gfmt_drv_6589_fmt.o gfmt_drv.o


# EOF
